### ISSUE TITLE
Add a catchWrong method similar to catchLeft

### ISSUE THREAD

**Issue by labra** [atnos-org/eff-cats#13]
Add a `catchWrong` method to `Validate` similar to `catchLeft` in `Xor`. 

The signature could be something like: 

```scala
catchLeft(r: Eff[R,A], handle: NonEmptyList[E] => Eff[R,A])(implicit m: Validate[E, ?] |= R): Eff[R, A]
```

**Comment by etorreborre** [comment]
See my [commit](https://github.com/atnos-org/eff-cats/commit/27820f9231e0c151edd160750d12731600e34e66). The signature is actually a bit different than what you expected because we handle one wrong value at the time. `NonEmptyList[E]` is only what we get once we decide to interpret `Validate` effects by accumulating validation errors in a `NonEmptyList`.
