### ISSUE TITLE
Scala.js build

### ISSUE THREAD

**Issue by ngbinh** [atnos-org/eff-cats#3]
Is it something you consider?  I can probably work on a PR due to our need.

**Comment by etorreborre** [comment]
This is a great idea! I haven't had a close look at what it means to have a Scala.js build but I'd be happy to receive a PR for that.

**Comment by ngbinh** [comment]
the main obstacle I can see now is the test as we don't have a scala.js build for specs2 yet. I can probably only run test on the JVM for now.

**Comment by etorreborre** [comment]
Unfortunately I need to find some time to work on [spec2#465](https://github.com/etorreborre/specs2/issues/465).

**Comment by benhutchison** [comment]
I could use this right now, got a cross-compiled lib I'd like to spike porting to Eff...

 What if we just ran the specs on the jvm branch for now, and mentioned in the docs that the scala.js build is "beta" ie not yet directly tested? From my experience of scala.js, I guess the kinds of things Eff does are unlikely to be problematic converted to js, since they're well away from platform details.
